---
title: "FINAL"
author: "Brahian Serna"
date: "2023-11-30"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Punto de lo huevos

```{r}
Tiempo <- c(4.30, 4.50, 5.0, 5.20, 6.0, 6.30, 7.0, 7.50, 8.0, 8.30, 8.50, 9.0, 9.30, 9.50, 10.0, 10.30, 10.40, 10.50, 11.0, 11.0, 11.30, 11.50, 12.0, 12.30, 12.50, 13.0, 13.20, 13.30, 13.50, 14.0)

 

Puntaje_huevo <- c(1.5, 1.7, 1.8, 2.1, 2.0, 2.4, 2.8, 3.0, 3.2, 3.4, 3.6, 3.8, 4.0, 4.5, 4.5, 4.8, 4.9, 5.0, 4.7, 4.3, 4.0, 3.9, 3.6, 3.3, 3.2, 2.8, 2.8, 2.5, 2.2, 2.0)

```


```{r}
plot(Tiempo,Puntaje_huevo)
```




```{r}

Briggs<-function(parametros){
d1<-parametros[1]
b1<-parametros[2]
e1<-parametros[3]
v1<-parametros[4]
Tiempo <-c(4.30, 4.50, 5.0, 5.20, 6.0, 6.30, 7.0, 7.50, 8.0, 8.30, 8.50, 9.0, 9.30, 9.50, 10.0, 10.30, 10.40, 10.50, 11.0, 11.0, 11.30, 11.50, 12.0, 12.30, 12.50, 13.0, 13.20, 13.30, 13.50, 14.0)


Puntaje_huevo <- c(1.5, 1.7, 1.8, 2.1, 2.0, 2.4, 2.8, 3.0, 3.2, 3.4, 3.6, 3.8, 4.0, 4.5, 4.5, 4.8, 4.9, 5.0, 4.7, 4.3, 4.0, 3.9, 3.6, 3.3, 3.2, 2.8, 2.8, 2.5, 2.2, 2.0)


modelo<-d1*exp(-b1*(Tiempo-e1)^2)
loglik<-sum(dnorm(Puntaje_huevo,mean=modelo,sd=sqrt(v1),log=T))
return(-loglik)
}

library(GenSA)

nimos<-c(0.1,0.001,0.1,0.1)
ximos<-c(50,50,50,100)
resu<-GenSA(c(1,1,1,1),Briggs,lower=nimos,upper=ximos)


resu$par

```

```{r}
Tiempo <-c(4.30, 4.50, 5.0, 5.20, 6.0, 6.30, 7.0, 7.50, 8.0, 8.30, 8.50, 9.0, 9.30, 9.50, 10.0, 10.30, 10.40, 10.50, 11.0, 11.0, 11.30, 11.50, 12.0, 12.30, 12.50, 13.0, 13.20, 13.30, 13.50, 14.0)

y.pred<-4.37340744*exp(-0.04378453*(Tiempo-9.98214541)^2)
Puntaje_huevo <- c(1.5, 1.7, 1.8, 2.1, 2.0, 2.4, 2.8, 3.0, 3.2, 3.4, 3.6, 3.8, 4.0, 4.5, 4.5, 4.8, 4.9, 5.0, 4.7, 4.3, 4.0, 3.9, 3.6, 3.3, 3.2, 2.8, 2.8, 2.5, 2.2, 2.0)
plot(Tiempo,Puntaje_huevo)
title(main="Tiempo vs. Puntaje de sabor")
#plot(Puntaje_huevo,y.pred)
points(Tiempo,y.pred,type="b",col="red")

```



#Punto Volumen vaciado de Tarro de Cocacola

```{r}
library(readxl)
datos <- read_excel("LITROS.xlsx")
```

```{r}
datos <- datos[datos$Tiempo!=0.0,]
plot(datos$Tiempo,datos$`Volumen en L`)
```


```{r}
library(nls2)

# Definir la función de decaimiento exponencial
modelo_exponencial <- function(tiempo, a, b) {
  a * exp(b * tiempo)
}


x <- datos$Tiempo
y <- as.numeric(datos$`Volumen en L`)

# Ajustar modelos con nls2
ajustes <- nls2(y ~ modelo_exponencial(x,a,b),
                start = c(a=30,b=-0.05))

# Mostrar resumen de los ajustes
summary(ajustes)
```


```{r}
plot(x,y)
points(x[order(x)],25.4722*exp(-0.17*x[order(x)]),type="b",col="red")

```


# Punto de los cerdos

```{r}
datos <- data.frame(semana = c(1:9,
                               1:9,
                               1:9,
                               1:9,
                               1:9),
                    Peso = c(24,30.5,36.5,44.5,48,51.5,59.5,66.5,65.5,
                             25.5,31,39,42,48,59,58,75.5,64,
                             30,32,39.5,47.5,55.5,56,56,63.5,67.5,
                             22.5,34.5,33,42,51.5,55.5,68,72.5,72.5,
                             24.5,33,39,43,43.5,56,62.5,73,80.5))
                  
```

```{r}
plot(datos$semana,datos$Peso)
```

```{r}
semanas <- datos$semana
pesos <- datos$Peso

library(nls2)

# Definir la función de decaimiento exponencial
modelo_polinomial <- function(semana, a, b, c) {
   c-b*(semanas-a)^2
}

# Ajustar modelos con nls2
ajustes <- nls2(pesos ~ modelo_polinomial(semanas,a,b,c),
                start = c(c=65,b=0.6,a=9))

# Mostrar resumen de los ajustes
summary(ajustes)
```

```{r}
plot(semanas,pesos)
points(semanas[order(semanas)],
       153.93176 - 0.08247*(semanas[order(semanas)]-40.50893)^2
       ,type="b",col="red")
```















